// Generated by https://quicktype.io
// Used for Create and Update
export class DowntimeGuide {
    id:             number;
    classification: string;
    description:    string;
    accountability: string;
}

// Generated by https://quicktype.io
// Used for Fetching List
export class DowntimeGuideList {
    id:                   number;
    classification:       string;
    description:          string;
    accountability:       string;
    createdDateTime:      string;
    lastModifiedDateTime: string;
}

// Generated by https://quicktype.io
// Used for Fetching by ID
export class DowntimeGuideId {
    id:                   number;
    classification:       string;
    description:          string;
    accountability:       string;
    createdDateTime:      string;
    lastModifiedDateTime: string;
}

