// Generated by https://quicktype.io

export class PlanningList {
    id:                   number;
    planningBatchId:      string;
    description:          string;
    createdDateTime:      string;
    lastModifiedDateTime: string;
}

// Generated by https://quicktype.io

export class PlanningById {
    id:                   number;
    planningBatchId:      string;
    description:          string;
    line1:                Line[];
    line2:                Line[];
    line3:                Line[];
    createdDateTime:      string;
    lastModifiedDateTime: string;
}

export class Line {
    id:                number;
    planningId:        number;
    sku:               string;
    description:       string;
    form:              string;
    mt:                number;
    actualHours:       number;
    effectiveCapacity: number;
    dieSizeThickness:  number;
    changeOver:        number;
    uncontrollable:    number;
    accountability:    string;
    delayStatus:       string;
    timeProduce:       number;
    remarks:           string;
    // planning:          Planning;
}

export class Planning {
    id:                   number;
    planningBatchId:      string;
    line1:                string[];
    line2:                string[];
    line3:                string[];
    description:          string;
    createdDateTime:      string;
    lastModifiedDateTime: string;
}

// Generated by https://quicktype.io

export class PlanningPost {
    id:                     number;
    description:            string;
    // planningBatchId:      string;
    // createdDateTime:      string;
    // lastModifiedDateTime: string;
}