// Generated by https://quicktype.io
// Used for Create and Update
export class ProductClassification {
    id:          number;
    code:        string;
    description: string;
}

// Generated by https://quicktype.io
// Used for Fetching List
export class ProductClassificationList {
    id:                   number;
    code:                 string;
    description:          string;
    createdDateTime:      string;
    lastModifiedDateTime: string;
}

// Generated by https://quicktype.io
// Used for Fetching by ID
export class ProductClassificationId {
    id:                   number;
    code:                 string;
    description:          string;
    createdDateTime:      string;
    lastModifiedDateTime: string;
}

